codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 70%
        threshold: 5%
    patch:
      default:
        target: 60%

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  - "demo.py"
  - "simple_demo.py"
  - "setup.py"
  - "run_tests.py"
  - "__pycache__"
  - "*.pyc"
